version: '3.7'

services:
 
 identity:
  image: "sitecore91.azurecr.io/sitecore-xc-identity:9.1.0-1809"
  command: -sitecoreHostname ${SITECORE_HOST_NAME} -identityHostname ${IDENTITY_HOST_NAME} -commerceHostname ${COMMERCE_HOST_NAME}
  volumes:
    - .\license:C:\license
  networks:
    - exampleNetwork   
  depends_on:
    - mssql

 commerce:
  ports: [22]
  image: "sitecore91.azurecr.io/sitecore-xc-commerce:9.1.0-1809"
  command: -commerceHostname ${COMMERCE_HOST_NAME} -sitecoreHostname ${SITECORE_HOST_NAME} -identityHostname ${IDENTITY_HOST_NAME}
  networks:
    exampleNetwork:
      aliases:
        - ${COMMERCE_HOST_NAME}
  volumes:
    - .\logs\commerce\CommerceAuthoring_Sc9:C:\inetpub\wwwroot\CommerceAuthoring_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceMinions_Sc9:C:\inetpub\wwwroot\CommerceMinions_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceOps_Sc9:C:\inetpub\wwwroot\CommerceOps_Sc9\wwwroot\logs
    - .\logs\commerce\CommerceShops_Sc9:C:\inetpub\wwwroot\CommerceShops_Sc9\wwwroot\logs
    - .\logs\commerce\SitecoreIdentityServer:C:\inetpub\wwwroot\SitecoreIdentityServer\wwwroot\logs
    - .\wwwroot\commerce\:C:\Workspace
  depends_on:
    - xconnect
    - mssql
    - solr
    - sitecore
    - identity


 mssql:
  image: "sitecore91.azurecr.io/sitecore-xc-mssql:9.1.0-1809"
  ports: [1403:1403]
  networks:
    - exampleNetwork 
  environment:
    ACCEPT_EULA: "Y"
    sa_password: ${SQL_SA_PASSWORD}
  volumes:
    - .\data\mssql:C:\Data
  
 sitecore:
  image: "sitecore91.azurecr.io/sitecore-xc-sitecore:9.1.0-1809"
  command: -commerceHostname ${COMMERCE_HOST_NAME} -identityHostname ${IDENTITY_HOST_NAME}
  networks:
    exampleNetwork:
      aliases:
        - ${SITECORE_HOST_NAME}
  volumes:
    - .\logs\sitecore:c:\inetpub\wwwroot\${SITECORE_SITE_NAME}\App_Data\logs
    - .\wwwroot\sitecore:C:\Workspace
    - .\license:C:\license    
  depends_on:
    - xconnect
    - mssql
    - solr
    - identity

  
 solr:
  image: "sitecore91.azurecr.io/sitecore-xc-solr:9.1.0-1809"
  ports: [8983]
  networks:
    - exampleNetwork 
  volumes:
    - .\data\solr:C:\Data
  
 xconnect:
  image: "sitecore91.azurecr.io/sitecore-xc-xconnect:9.1.0-1809"
  ports: [443]
  networks:
    - exampleNetwork 
  volumes:
    - .\logs\xconnect:C:\inetpub\wwwroot\xconnect\App_data\Logs
    - .\license:C:\license    
  depends_on:
    - mssql
    - solr

networks:
  exampleNetwork:
    external:
      name: nat